/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
@epoch-2 train 0.531
@epoch-2 train 0.531
val 0.522
val 0.522
test 0.549
test 0.549
* validation accuracy improved *
* validation accuracy improved *
best test accuracy 0.549
best test accuracy 0.549
@epoch-3 train 0.575
@epoch-3 train 0.575
val 0.514
val 0.514
test 0.557
test 0.557
best test accuracy 0.549
best test accuracy 0.549
@epoch-4 train 0.595
@epoch-4 train 0.595
val 0.529
val 0.529
test 0.560
test 0.560
* validation accuracy improved *
* validation accuracy improved *
best test accuracy 0.560
best test accuracy 0.560
@epoch-5 train 0.615
@epoch-5 train 0.615
val 0.521
val 0.521
test 0.557
test 0.557
best test accuracy 0.560
best test accuracy 0.560
@epoch-6 train 0.633
@epoch-6 train 0.633
val 0.529
val 0.529
test 0.562
test 0.562
best test accuracy 0.560
best test accuracy 0.560
Program interrupted. (Use 'cont' to resume).
Traceback (most recent call last):
  File "changeit3d/notebooks/cs766/exp_c_listener_training.py", line 183, in <module>
    df = pd.read_csv(args.shape_talk_file)
  File "changeit3d/notebooks/cs766/exp_c_listener_training.py", line 99, in exp_c_train_listener
    train_results = single_epoch_train(model,
  File "/home/shared/changeit3d/changeit3d/models/listening_oriented.py", line 212, in single_epoch_train
    for batch in train_loader:
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_fd
    fd = df.detach()
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 380, in _recv
    n = len(chunk)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/multiprocessing/connection.py", line 380, in _recv
    n = len(chunk)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/pdb.py", line 351, in interaction
    if self.setup(frame, traceback):
  File "/home/aharish2/miniconda3/envs/c3d/lib/python3.8/pdb.py", line 221, in setup
    self.curframe_locals = self.curframe.f_locals
KeyboardInterrupt